### ISSUE TITLE
Neon and related

### ISSUE THREAD

**Issue by jianshu93** [Daniel-Liu-c0deb0t/block-aligner#4]
Hello Daniel,

Can you please show some example on how to support Neon on MacOS M1 and M1 Pro/Max with this? Another question is related: the simdeez library only supports avx2 and sse2. How to allow support for neon, which library?

THanks,

Jianshu

**Comment by Daniel-Liu-c0deb0t** [comment]
It would require a bit of work to support Neon with the library as it is currently. My implementation directly uses my own wrapper for SIMD instructions, so a separate wrapper needs to be made for Neon. Do you need this feature?

I'm not sure how simdeez works in detail, since I did not use it in this library.

**Comment by tfenne** [comment]
Just chiming in to say that I'm actively using block-aligner, and have moved to an M1* laptop recently, and would also really like neon support.  I have several reasons for keeping an older x86 laptop around, but they are dwindling fast, and this is one of them.

**Comment by Daniel-Liu-c0deb0t** [comment]
Neon support should be added in the latest commit (PR #17)!

**Comment by jianshu93** [comment]
Tests showed that it works on my m1 pro.

Many thanks！

Jianshu
